### PR TITLE
Edit from draft in order to get to commits-Dinner

### PR DESCRIPTION
**Pull request by cailintodd**
Changed the process in order to get to the proper commit channel. Apologies team!

## 🎯 Objective

_Note why you're making this change and any relevant issues_
The formatting from the initial draft did not look right with the bullet points. Also, need review from rest of the team via pull requests. 

## 🛠️ Changes made
No dashes for the list vs. dashes

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 
@gwrightsimmons @tai-wu @Aloha15 @fcovarr1 
_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._
Feel free to edit as needed, team!

### CODE REVIEW

**Review by Aloha15 — APPROVED** [review]
Looks good!

**Review by tai-wu — APPROVED** [review]
Looks good

**Review by gwrightsimmons — COMMENTED** [review]
This recipe uses numbers for the instructions--do we want to repeat that pattern for the breakfast and lunch recipes too?

**Comment by gwrightsimmons** [comment]
Made the final edits and this one looks good to go 🚀

**Pull request merged**
