### PR TITLE
Lunch Recipe Draft 1

### PR DESCRIPTION
**Pull request by cailintodd**
Added plus signs to the ingredients so it is cohesive with the rest of the recipes. Added tongs as equipment as well as put initial headers underneath their categories.

## 🎯 Objective
Modify Tai's initial draft of the lunch recipe.
_Note why you're making this change and any relevant issues_

## 🛠️ Changes made
Formatting of ingredients and steps, added a tool 
_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 
@tai-wu @Aloha15 @gwrightsimmons @fcovarr1 
_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by Aloha15 — APPROVED** [review]
Looks great

**Review by tai-wu — APPROVED** [review]
Looks good, team.

**Review by fcovarr1 — APPROVED** [review]
Looks great!

**Review by fcovarr1 — APPROVED** [review]
OK

**Review by gwrightsimmons — COMMENTED** [review]
Can someone double check my estimate for the BBQ Pork prep and cook times?

**Comment by tai-wu** [comment]
Team, we have a conflict we have to resolve here. I say the recipe takes "20 minutes - 30 minute" versus "20 minutes" to give it a range. Let me know your thoughts. @Aloha15 @gwrightsimmons @fcovarr1 @gwrightsimmons

**Review by fcovarr1 — APPROVED** [review]

**Comment by fcovarr1** [comment]
Hi everyone! We also have a conflict on the final recommendation (about waiting 5 minutes before serving). Considering the details of both conflicts, I believe the last commit was made over an outdated version. Could be?

**Comment by gwrightsimmons** [comment]
+1 to 20-30 minutes. I think a range makes sense here

**Review by Aloha15 — APPROVED** [review]

**Comment by gwrightsimmons** [comment]
Removed merge conflicts and pushed to master

**Pull request merged**
