### PR TITLE
New recommendation

### PR DESCRIPTION
**Pull request by fcovarr1**
Recommendation at the end

## 🎯 Objective

Offer a better experience

## 🛠️ Changes made

Recommendation at the end

## 👥 Who needs to review this Pull Request? 

@stalerat _ @gwrightsimmons  @Aloha15  @cailintodd

### CODE REVIEW

**Review by cailintodd — APPROVED** [review]
Thanks so much for the work team. I approve!

**Review by Aloha15 — APPROVED** [review]
Like these changes!

**Review by tai-wu — APPROVED** [review]
Look nice. Good job.

**Review by cailintodd — APPROVED** [review]
I approve the idea of waiting so food isn't too hot. Approve!

**Pull request merged**
